name: ci

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
      # Test that we have the correct version of GO.
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26.0'

      # CI Tests Fail when any of the tests fail
      - name: Force Failure
        run: (exit 1)
